on:
  push:
    branches:
      - main
  schedule:
    - cron:  '05 4 * * *'
permissions:
  contents: write
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: setup uv (python)
      uses: astral-sh/setup-uv@v5
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: run data pulls
      run: |-
        bundle exec rake start
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push origin HEAD:main
